name: hs
on:
  push:
    branches: ['main']
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          cd ${{github.workspace}}/hs/bzlmod
          ${{github.workspace}}/bazelisk run :example
